# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

project_name: fthelper

gomod:
  proxy: true

builds:
  - id: ftgenerator
    binary: ftgenerator
    dir: generator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '6'
      - '7'
  - id: ftmetric
    binary: ftmetric
    dir: metric
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '6'
      - '7'

archives:
  - id: ftgenerator
    format: binary
    builds:
      - ftgenerator
  - id: ftmetric
    format: binary
    builds:
      - ftmetric

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - ftgenerator
    skip_push: false
    use: buildx
    dockerfile: generator/docker/Dockerfile.busybox
    image_templates:
      - "ghcr.io/frysee/ftgenerator:amd64"
      - "ghcr.io/frysee/ftgenerator:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftgenerator"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=amd64"
      - "--platform=linux/amd64"
    extra_files:
      - generator/.env.docker
      - generator/configs
  - goos: linux
    goarch: amd64
    ids:
      - ftgenerator
    skip_push: false
    use: buildx
    dockerfile: generator/docker/Dockerfile.stratch
    image_templates:
      - "ghcr.io/frysee/ftgenerator:amd64-stratch"
      - "ghcr.io/frysee/ftgenerator:{{ .Tag }}-amd64-stratch"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftgenerator"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=amd64"
      - "--platform=linux/amd64"
    extra_files:
      - generator/.env.docker
      - generator/configs
  - goos: linux
    goarch: arm64
    ids:
      - ftgenerator
    skip_push: false
    use: buildx
    dockerfile: generator/docker/Dockerfile.busybox
    image_templates:
      - "ghcr.io/frysee/ftgenerator:arm64"
      - "ghcr.io/frysee/ftgenerator:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftgenerator"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=arm64"
      - "--platform=linux/arm64"
    extra_files:
      - generator/.env.docker
      - generator/configs
  - goos: linux
    goarch: arm64
    ids:
      - ftgenerator
    skip_push: false
    use: buildx
    dockerfile: generator/docker/Dockerfile.stratch
    image_templates:
      - "ghcr.io/frysee/ftgenerator:arm64-stratch"
      - "ghcr.io/frysee/ftgenerator:{{ .Tag }}-arm64-stratch"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftgenerator"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=arm64"
      - "--platform=linux/arm64"
    extra_files:
      - generator/.env.docker
      - generator/configs
  - goos: linux
    goarch: arm
    goarm: '6'
    ids:
      - ftgenerator
    skip_push: false
    use: buildx
    dockerfile: generator/docker/Dockerfile.busybox
    image_templates:
      - "ghcr.io/frysee/ftgenerator:armv6"
      - "ghcr.io/frysee/ftgenerator:{{ .Tag }}-armv6"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftgenerator"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=armv6"
      - "--platform=linux/arm/v6"
    extra_files:
      - generator/.env.docker
      - generator/configs
  - goos: linux
    goarch: arm
    goarm: '6'
    ids:
      - ftgenerator
    skip_push: false
    use: buildx
    dockerfile: generator/docker/Dockerfile.stratch
    image_templates:
      - "ghcr.io/frysee/ftgenerator:armv6-stratch"
      - "ghcr.io/frysee/ftgenerator:{{ .Tag }}-armv6-stratch"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftgenerator"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=armv6"
      - "--platform=linux/arm/v6"
    extra_files:
      - generator/.env.docker
      - generator/configs
  - goos: linux
    goarch: arm
    goarm: '7'
    ids:
      - ftgenerator
    skip_push: false
    use: buildx
    dockerfile: generator/docker/Dockerfile.busybox
    image_templates:
      - "ghcr.io/frysee/ftgenerator:armv7"
      - "ghcr.io/frysee/ftgenerator:{{ .Tag }}-armv7"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftgenerator"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=armv7"
      - "--platform=linux/arm/v7"
    extra_files:
      - generator/.env.docker
      - generator/configs
  - goos: linux
    goarch: arm
    goarm: '7'
    ids:
      - ftgenerator
    skip_push: false
    use: buildx
    dockerfile: generator/docker/Dockerfile.stratch
    image_templates:
      - "ghcr.io/frysee/ftgenerator:armv7-stratch"
      - "ghcr.io/frysee/ftgenerator:{{ .Tag }}-armv7-stratch"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftgenerator"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=armv7"
      - "--platform=linux/arm/v7"
    extra_files:
      - generator/.env.docker
      - generator/configs

  - goos: linux
    goarch: amd64
    ids:
      - ftmetric
    skip_push: false
    use: buildx
    dockerfile: metric/docker/Dockerfile.busybox
    image_templates:
      - "ghcr.io/frysee/ftmetric:amd64"
      - "ghcr.io/frysee/ftmetric:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftmetric"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=amd64"
      - "--platform=linux/amd64"
    extra_files:
      - metric/.env.docker
      - metric/configs
  - goos: linux
    goarch: amd64
    ids:
      - ftmetric
    skip_push: false
    use: buildx
    dockerfile: metric/docker/Dockerfile.stratch
    image_templates:
      - "ghcr.io/frysee/ftmetric:amd64-stratch"
      - "ghcr.io/frysee/ftmetric:{{ .Tag }}-amd64-stratch"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftmetric"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=amd64"
      - "--platform=linux/amd64"
    extra_files:
      - metric/.env.docker
      - metric/configs
  - goos: linux
    goarch: arm64
    ids:
      - ftmetric
    skip_push: false
    use: buildx
    dockerfile: metric/docker/Dockerfile.busybox
    image_templates:
      - "ghcr.io/frysee/ftmetric:arm64"
      - "ghcr.io/frysee/ftmetric:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftmetric"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=arm64"
      - "--platform=linux/arm64"
    extra_files:
      - metric/.env.docker
      - metric/configs
  - goos: linux
    goarch: arm64
    ids:
      - ftmetric
    skip_push: false
    use: buildx
    dockerfile: metric/docker/Dockerfile.stratch
    image_templates:
      - "ghcr.io/frysee/ftmetric:arm64-stratch"
      - "ghcr.io/frysee/ftmetric:{{ .Tag }}-arm64-stratch"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftmetric"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=arm64"
      - "--platform=linux/arm64"
    extra_files:
      - metric/.env.docker
      - metric/configs
  - goos: linux
    goarch: arm
    goarm: '6'
    ids:
      - ftmetric
    skip_push: false
    use: buildx
    dockerfile: metric/docker/Dockerfile.busybox
    image_templates:
      - "ghcr.io/frysee/ftmetric:armv6"
      - "ghcr.io/frysee/ftmetric:{{ .Tag }}-armv6"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftmetric"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=armv6"
      - "--platform=linux/arm/v6"
    extra_files:
      - metric/.env.docker
      - metric/configs
  - goos: linux
    goarch: arm
    goarm: '6'
    ids:
      - ftmetric
    skip_push: false
    use: buildx
    dockerfile: metric/docker/Dockerfile.stratch
    image_templates:
      - "ghcr.io/frysee/ftmetric:armv6-stratch"
      - "ghcr.io/frysee/ftmetric:{{ .Tag }}-armv6-stratch"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftmetric"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=armv6"
      - "--platform=linux/arm/v6"
    extra_files:
      - metric/.env.docker
      - metric/configs
  - goos: linux
    goarch: arm
    goarm: '7'
    ids:
      - ftmetric
    skip_push: false
    use: buildx
    dockerfile: metric/docker/Dockerfile.busybox
    image_templates:
      - "ghcr.io/frysee/ftmetric:armv7"
      - "ghcr.io/frysee/ftmetric:{{ .Tag }}-armv7"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftmetric"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=armv7"
      - "--platform=linux/arm/v7"
    extra_files:
      - metric/.env.docker
      - metric/configs
  - goos: linux
    goarch: arm
    goarm: '7'
    ids:
      - ftmetric
    skip_push: false
    use: buildx
    dockerfile: metric/docker/Dockerfile.stratch
    image_templates:
      - "ghcr.io/frysee/ftmetric:armv7-stratch"
      - "ghcr.io/frysee/ftmetric:{{ .Tag }}-armv7-stratch"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ftmetric"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.tag={{ .Tag }}"
      - "--build-arg=FTH_SERVER__ARCH=armv7"
      - "--platform=linux/arm/v7"
    extra_files:
      - metric/.env.docker
      - metric/configs

docker_manifests:
  - name_template: ghcr.io/frysee/ftgenerator:{{ .Tag }}
    image_templates:
      - ghcr.io/frysee/ftgenerator:{{ .Tag }}-amd64
      - ghcr.io/frysee/ftgenerator:{{ .Tag }}-arm64
      - ghcr.io/frysee/ftgenerator:{{ .Tag }}-armv6
      - ghcr.io/frysee/ftgenerator:{{ .Tag }}-armv7
  - name_template: ghcr.io/frysee/ftgenerator:latest
    image_templates:
      - ghcr.io/frysee/ftgenerator:amd64
      - ghcr.io/frysee/ftgenerator:arm64
      - ghcr.io/frysee/ftgenerator:armv6
      - ghcr.io/frysee/ftgenerator:armv7
  - name_template: ghcr.io/frysee/ftgenerator:{{ .Tag }}-stratch
    image_templates:
      - ghcr.io/frysee/ftgenerator:{{ .Tag }}-amd64-stratch
      - ghcr.io/frysee/ftgenerator:{{ .Tag }}-arm64-stratch
      - ghcr.io/frysee/ftgenerator:{{ .Tag }}-armv6-stratch
      - ghcr.io/frysee/ftgenerator:{{ .Tag }}-armv7-stratch
  - name_template: ghcr.io/frysee/ftgenerator:stratch
    image_templates:
      - ghcr.io/frysee/ftgenerator:amd64-stratch
      - ghcr.io/frysee/ftgenerator:arm64-stratch
      - ghcr.io/frysee/ftgenerator:armv6-stratch
      - ghcr.io/frysee/ftgenerator:armv7-stratch

  - name_template: ghcr.io/frysee/ftmetric:{{ .Tag }}
    image_templates:
      - ghcr.io/frysee/ftmetric:{{ .Tag }}-amd64
      - ghcr.io/frysee/ftmetric:{{ .Tag }}-arm64
      - ghcr.io/frysee/ftmetric:{{ .Tag }}-armv6
      - ghcr.io/frysee/ftmetric:{{ .Tag }}-armv7
  - name_template: ghcr.io/frysee/ftmetric:latest
    image_templates:
      - ghcr.io/frysee/ftmetric:amd64
      - ghcr.io/frysee/ftmetric:arm64
      - ghcr.io/frysee/ftmetric:armv6
      - ghcr.io/frysee/ftmetric:armv7
  - name_template: ghcr.io/frysee/ftmetric:{{ .Tag }}-stratch
    image_templates:
      - ghcr.io/frysee/ftmetric:{{ .Tag }}-amd64-stratch
      - ghcr.io/frysee/ftmetric:{{ .Tag }}-arm64-stratch
      - ghcr.io/frysee/ftmetric:{{ .Tag }}-armv6-stratch
      - ghcr.io/frysee/ftmetric:{{ .Tag }}-armv7-stratch
  - name_template: ghcr.io/frysee/ftmetric:stratch
    image_templates:
      - ghcr.io/frysee/ftmetric:amd64-stratch
      - ghcr.io/frysee/ftmetric:arm64-stratch
      - ghcr.io/frysee/ftmetric:armv6-stratch
      - ghcr.io/frysee/ftmetric:armv7-stratch

release:
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore"
      - "^refac"
